#!/usr/bin/env bash
# shellcheck disable=SC2086

set -eu
set -o pipefail
# set -x

### TEI transformation for PAGE-XML in OCR-D
# 
# Uses an XSL transformation to convert and aggregate the PAGE-XML
# files of the input file group to a single TEI-XML file. The result
# is added to the output fileGrp.

which ocrd >/dev/null 2>/dev/null || { echo >&2 "ocrd not in \$PATH. Panicking"; exit 1; }
((BASH_VERSINFO<4 || BASH_VERSINFO==4 && BASH_VERSINFO[1]<4)) && echo >&2 "bash $BASH_VERSION is too old. Please install bash 4.4 or newer." && exit 1

SHAREDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SAXONLIB=saxon-he-10.6.jar
MIMETYPE_PAGE=$(ocrd bashlib constants MIMETYPE_PAGE)

    
function main {
    # Load ocrd bashlib functions
    # shellcheck source=../core/ocrd/bashlib/lib.bash
    source $(ocrd bashlib filename)
    ocrd__wrap "$SHAREDIR/ocrd-tool.json" "ocrd-page2tei" "$@"
    ocrd__minversion 2.30.0

    xsl=page2tei-0.xsl
    if test -e "$xsl"; then
        xsl="$(realpath "$xsl")"
    elif test -e "$SHAREDIR/$xsl"; then
        xsl="$SHAREDIR/$xsl"
    elif ocrd__list_resources | fgrep -q "/$xsl"; then
        xsl="$(ocrd__list_resources | fgrep -m1 "/$xsl")"
    else
        ocrd__raise "cannot find xsl resource '$xsl'"
    fi
    saxon=$SAXONLIB
    if test -e "$saxon"; then
        saxon="$(realpath "$saxon")"
    elif test -e "$SHAREDIR/$saxon"; then
        saxon="$SHAREDIR/$saxon"
    elif ocrd__list_resources | fgrep -q "/$saxon"; then
        saxon="$(ocrd__list_resources | fgrep -m1 "/$saxon")"
    else
        ocrd__raise "cannot find Saxon resource '$saxon'"
    fi
    cd "${ocrd__argv[working_dir]}"
    inp_file_grp=${ocrd__argv[input_file_grp]}
    out_file_grp=${ocrd__argv[output_file_grp]}
    out_id=${out_file_grp}_TEI
    out_fpath=${out_file_grp}/${out_id}.xml

    mkdir -p $out_file_grp
    # Transform
    java -jar "$saxon" -xsl:"$xsl" -s:mets.xml PAGEXML=${inp_file_grp} PAGEprogram=OCRD -o:"$out_fpath"

    # Add TEI file to METS
    declare -a options
    if [[ "${ocrd__argv[overwrite]}" == true ]];then
        options+=( --force )
    fi
    options+=( -G $out_file_grp
               -m $MIMETYPE_PAGE
               -i "$out_id"
               "$out_fpath" )
    ocrd workspace add "${options[@]}"
}


main "$@"
